import { WorkOrder, WorkOrderStatus } from "./orderSlice";

export abstract class WorkOrdersMocks {
  //   public static readonly initialWorkOrders: WorkOrder[] = [
  //     {
  //       id: "6b5ada65-21cf-402a-8458-8eaee2567161",
  //       receiptDate: "2023-05-01",
  //       deliveryDate: "2023-05-10",
  //       licensePlate: "EEAR44",
  //       items: ["Cambio de aceite", "Cambio de filtro de aceite"],
  //       notes: "El cliente se queja de un ruido en el motor",
  //       responsibleMechanic: "Juan Alcadiez",
  //       responsibleMechanicId: "1",
  //       status: "Pendiente",
  //       cost: 12500,
  //     },
  //     {
  //       id: "cb697a4c-dbdb-4540-b640-bc974502c1c2",
  //       receiptDate: "2023-05-01",
  //       deliveryDate: "2023-05-10",
  //       licensePlate: "EMJF23",
  //       items: ["Balanceo", "Cambio de correa de distribución"],
  //       notes: "El cliente se queja de un ruido en el motor",
  //       responsibleMechanic: "Juan Alcadiez",
  //       responsibleMechanicId: "1",
  //       status: "En progreso",
  //       cost: 50000,
  //     },

  //     {
  //       id: "fe375b21-0930-43f5-93c2-772789e4d052",
  //       receiptDate: "2023-05-04",
  //       deliveryDate: "2023-05-12",
  //       licensePlate: "EMJF23",
  //       items: ["Balanceo", "Cambio de correa de distribución"],
  //       notes: "El cliente se queja de un ruido en el motor",
  //       responsibleMechanic: "Juan Alcadiez",
  //       responsibleMechanicId: "1",
  //       status: "En progreso",
  //       cost: 50000,
  //     },
  //   ];

  public static reparationItems: string[] = [
    "cambio de aceite",
    "cambio de llantas",
    "reparación de frenos",
    "reparación de transmisión",
    "reparación de motor",
    "cambio de motor",
    "desabolladura",
    "pintura",
    "reparación de carrocería",
    "reparación de suspensión",
    "reparación de suspensión",
    "reparación de aire acondicionado",
    "alineación y balanceo",
    "cambio de batería",
    "cambio de bujías",
    "cambio de filtro de aire",
    "cambio de filtro de aceite",
    "cambio de filtro de combustible",
    "cambio de líquido de frenos",
    "cambio de líquido de transmisión",
    "cambio de pastillas de freno",
    "cambio de rotor de freno",
    "cambio de termostato",
    "cambio de bomba de agua",
    "cambio de correa de distribución",
    "cambio de correa de accesorios",
    "reparación de sistema eléctrico",
    "reparación de sistema de escape",
    "reparación de sistema de dirección",
    "reparación de sistema de combustible",
    "reparación de sistema de refrigeración",
    "Otro",
  ];

  public static readonly initialWorkOrders: WorkOrder[] = [
    {
      id: "0b70257e-ff3e-4534-ba9a-c0ba027b02d2",
      receiptDate: "2023-03-29",
      deliveryDate: "2023-05-22",
      licensePlate: "KMHG77",
      items: ["reparación de sistema eléctrico"],
      notes:
        "pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi",
      responsibleMechanic: "Sabra Marcq",
      responsibleMechanicId: "46ff70e4-1cb4-4de1-aa54-8f2c45966029",
      status: "Pendiente",
      cost: 89800,
    },
    {
      id: "1b6a9c33-25f9-4b96-a878-dc3be7d38df5",
      receiptDate: "2022-12-02",
      deliveryDate: "2022-12-04",
      licensePlate: "3D73Y4",
      items: ["cambio de termostato", "cambio de aceite"],
      notes: "sapien in sapien iaculis congue vivamus",
      responsibleMechanic: "Jae Pettigrew",
      responsibleMechanicId: "21dcf604-2581-4b8c-9c16-d704a19e3f2c",
      status: "Pendiente",
      cost: 89800,
    },
    {
      id: "91b187ed-b1b9-47cb-a881-19a2826b4636",
      receiptDate: "2022-10-12",
      deliveryDate: "2022-06-04",
      licensePlate: "JM1NC2",
      items: ["reparación de aire acondicionado"],
      notes:
        "non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra",
      responsibleMechanic: "Angelia Bevis",
      responsibleMechanicId: "67772cb7-487f-4012-b90c-796fcb51a9e4",
      status: "En progreso",
      cost: 89800,
    },
    {
      id: "0e6dd546-b66d-46d5-91cf-3ea6483d55ea",
      receiptDate: "2022-10-22",
      deliveryDate: "2023-07-15",
      licensePlate: "JH4NA1",
      items: ["cambio de aceite"],
      notes:
        "magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed",
      responsibleMechanic: "Obie McAusland",
      responsibleMechanicId: "ea6f5f06-6353-4447-9635-9f93c33082bf",
      status: "En progreso",

      cost: 89800,
    },
    {
      id: "ec93259d-9ff1-4888-82fe-ec5d9a605389",
      receiptDate: "2023-01-01",
      deliveryDate: "2023-04-20",
      licensePlate: "JH4NA1",
      items: ["cambio de filtro de aceite"],
      notes:
        "nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis",
      responsibleMechanic: "Dahlia Rowling",
      responsibleMechanicId: "98f8a572-17c7-4fba-94a6-2117fb51abd9",
      status: "En progreso",

      cost: 89800,
    },
    {
      id: "8deb33a1-a923-4ea0-bdd9-801a9faea731",
      receiptDate: "2022-04-08",
      deliveryDate: "2021-12-19",
      licensePlate: "WDDEJ7",
      items: ["reparación de sistema de escape"],
      notes:
        "lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa.",
      responsibleMechanic: "Doris Cardillo",
      responsibleMechanicId: "d6a15b09-a659-4d35-a8a8-4b7aeb0bcc4d",
      status: "Cancelado",
      cost: 45000,
    },
    {
      id: "b011d210-b495-4c30-aaf5-9461ec672402",
      receiptDate: "2022-12-21",
      deliveryDate: "2022-11-02",
      licensePlate: "19UUA8",
      items: ["cambio de aceite"],
      notes:
        "luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est",
      responsibleMechanic: "Prince Milverton",
      responsibleMechanicId: "d6a46abb-677f-47c7-8ac2-2086fe91d235",
      status: "Cancelado",
      cost: 32000,
    },
    {
      id: "563caa13-c4bc-470d-8d3f-6cfec0efb9ec",
      receiptDate: "2022-09-15",
      deliveryDate: "2022-11-04",
      licensePlate: "1G6DP5",
      items: ["cambio de batería"],
      notes:
        "nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio.",
      responsibleMechanic: "Abram Welberry",
      responsibleMechanicId: "79627b34-3d29-4c18-9456-a59090b9ec86",
      status: "Facturado",

      cost: 25000,
    },
    {
      id: "b97464a9-7991-4024-bdcf-f7f75c7780f3",
      receiptDate: "2022-05-23",
      deliveryDate: "2022-07-07",
      licensePlate: "1G6AK5",
      items: ["cambio de llantas"],
      notes:
        "elementum ligula vehicula consequat morbi a ipsum integer a nibh.",
      responsibleMechanic: "Constancia Doorbar",
      responsibleMechanicId: "d1066990-c7b4-4d8d-bf43-8b23552cf4b8",
      status: "Facturado",
      cost: 50000,
    },
    {
      id: "1e12e97c-218b-41f2-84a5-cddec97e983e",
      receiptDate: "2022-06-08",
      deliveryDate: "2022-02-24",
      licensePlate: "WBANW1",
      items: ["cambio de correa de accesorios"],
      notes: "vulputate",
      responsibleMechanic: "Garrott Woolerton",
      status: "Facturado",
      responsibleMechanicId: "765c21fc-156d-4b4b-8e9e-17ee243853dc",
      cost: 59000,
    },
    {
      id: "3d9cd680-ec45-4a31-8e8c-7702b5e68a05",
      receiptDate: "2023-05-19",
      deliveryDate: "2022-01-03",
      licensePlate: "19XFB4",
      items: ["cambio de filtro de aceite", "Otros"],
      notes:
        "volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",
      responsibleMechanic: "Ertha Devine",
      responsibleMechanicId: "76f18d08-66c4-44c3-9257-c7a3eb5fc557",
      status: "Facturado",
      cost: 70000,
    },
    {
      id: "c9737eee-d60d-4217-acd8-072cb7c87f23",
      receiptDate: "2023-01-20",
      deliveryDate: "2023-01-15",
      licensePlate: "5UXZV4",
      items: ["reparación de sistema de escape"],
      notes:
        "nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec",
      responsibleMechanic: "Tove Kenefick",
      responsibleMechanicId: "df4151c7-8714-422a-a276-53dc895636f8",
      status: "Facturado",

      cost: 150000,
    },
    {
      id: "e31e7487-7b0f-40f2-9a7f-3bfacdba85bf",
      receiptDate: "2022-11-07",
      deliveryDate: "2022-05-14",
      licensePlate: "2G4WE5",
      items: ["cambio de aceite"],
      notes: "",
      responsibleMechanic: "Nadean Gillebert",
      responsibleMechanicId: "2cb48a66-3e24-426d-ae86-7cd35f614847",
      status: "Facturado",

      cost: 25000,
    },
    {
      id: "1d8612e3-6774-4356-8d0e-382df7050a4b",
      receiptDate: "2021-12-20",
      deliveryDate: "2022-08-27",
      licensePlate: "JH4KB1",
      items: ["cambio de aceite"],
      notes: "",
      responsibleMechanic: "Reginald Moorton",
      responsibleMechanicId: "cb46a9ec-c057-41d5-9a19-7c36d171ba4c",
      status: "Facturado",
      cost: 25000,
    },
    {
      id: "86e067f0-ff94-4bf3-9d40-47be54552930",
      receiptDate: "2022-09-01",
      deliveryDate: "2022-03-27",
      licensePlate: "4T1BF1",
      items: ["reparación de motor"],
      notes: "sit",
      responsibleMechanic: "Barnie Hosby",
      responsibleMechanicId: "792dbfbb-9662-48ae-b8f4-95cfd8f62342",
      status: "Cancelado",
      cost: 1150000,
    },
    {
      id: "66f3441d-9172-4f8e-a456-a2b745109f49",
      receiptDate: "2022-10-25",
      deliveryDate: "2022-08-02",
      licensePlate: "JH4CU",
      items: ["cambio de correa de distribución"],
      notes:
        "vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae",
      responsibleMechanic: "Dean Stilldale",
      responsibleMechanicId: "83e42627-6206-493f-9452-da7483a2ab8f",
      status: "Cancelado",
      cost: 30000,
    },
    {
      id: "dd1f9c5f-66fe-4c0d-8734-b4c7831e4087",
      receiptDate: "2022-07-29",
      deliveryDate: "2022-05-10",
      licensePlate: "WAUDG4",
      items: ["alineación y balanceo"],
      notes:
        "id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
      responsibleMechanic: "Ewen Drinan",
      responsibleMechanicId: "8e308210-6cd2-4766-9cf8-8f713c482163",
      status: "Pendiente",
      cost: 200000,
    },
    {
      id: "c8d6e171-b55d-436c-a6e5-96c99a7833e7",
      receiptDate: "2023-03-30",
      deliveryDate: "2022-02-25",
      licensePlate: "1GYFK5",
      items: ["reparación de motor"],
      notes:
        "augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra",
      responsibleMechanic: "Cathleen Matschoss",
      responsibleMechanicId: "3907b7d0-146b-4910-aa71-2b2dcb3a381e",
      status: "Pendiente",
      cost: 500000,
    },
    {
      id: "01d147cd-6440-486f-b5e0-d5fa316a7bc3",
      receiptDate: "2022-05-31",
      deliveryDate: "2023-02-10",
      licensePlate: "WAUMFB",
      items: ["cambio de batería"],
      notes:
        "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam",
      responsibleMechanic: "Ulrike Roome",
      responsibleMechanicId: "4b4127fe-f2b7-45f5-8704-a48e82ffc4ab",
      status: "Pendiente",
      cost: 27000,
    },
    {
      id: "36b09c36-f8d6-4f27-94f7-7b8ac61ddcd3",
      receiptDate: "2023-04-13",
      deliveryDate: "2023-02-04",
      licensePlate: "WAUFFA",
      items: ["cambio de filtro de aceite"],
      notes:
        "tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus",
      responsibleMechanic: "Kirbee Dmitr",
      responsibleMechanicId: "bc564262-8d73-4f24-81b7-9c774ffdb868",
      status: "Pendiente",

      cost: 15000,
    },
    {
      id: "f896e5a8-b8de-44a2-8ac2-adf3af500633",
      receiptDate: "2022-03-01",
      deliveryDate: "2023-06-24",
      licensePlate: "1FTWX3",
      items: ["cambio de pastillas de freno"],
      notes:
        "purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit",
      responsibleMechanic: "Sisely Gaffer",
      responsibleMechanicId: "7c6edc70-b776-4109-a1c4-c1a1094638d5",
      status: "Pendiente",

      cost: 90000,
    },
    {
      id: "a4f4b14a-600e-4e5d-aa09-4c18a1cab892",
      receiptDate: "2023-04-06",
      deliveryDate: "2023-05-06",
      licensePlate: "1G6KD5",
      items: ["reparación de transmisión"],
      notes: "",
      responsibleMechanic: "Valli Rembrandt",
      responsibleMechanicId: "e60a77db-2e84-49c6-be59-b3adf6147c7a",
      status: "Facturado",
      cost: 190000,
    },
    {
      id: "a9278202-f930-4e69-a34a-c009b450e4af",
      receiptDate: "2022-04-07",
      deliveryDate: "2022-12-08",
      licensePlate: "5UXWX9",
      items: ["reparación de motor"],
      notes:
        "vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci",
      responsibleMechanic: "Isak Notton",
      responsibleMechanicId: "33e3be40-0338-432b-9f5c-428a8e894c33",
      status: "Facturado",
      cost: 1600000,
    },
    {
      id: "34dd9ac3-7612-4dc4-98fb-41adb19c6cd1",
      receiptDate: "2022-12-11",
      deliveryDate: "2022-10-06",
      licensePlate: "YV1672",
      items: ["reparación de sistema de escape"],
      notes: "",
      responsibleMechanic: "Genia Celle",
      responsibleMechanicId: "e6325879-ab78-4372-97eb-96573be72e2d",
      status: "Cancelado",
      cost: 50000,
    },
    {
      id: "54751b0f-2d3e-4b4f-9bca-b33c198a9a01",
      receiptDate: "2023-04-12",
      deliveryDate: "2023-04-01",
      licensePlate: "2G4GR5",
      items: ["reparación de suspensión"],
      notes:
        "pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum",
      responsibleMechanic: "Wilhelmina Bilborough",
      responsibleMechanicId: "ddcf8749-f9df-4506-90bf-cf9bb579e8ae",
      status: "Cancelado",
      cost: 200000,
    },
  ];
}
